project:
  type: website

website:
  title: "Dhruv Garg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
    right:
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/vrudhgarg
      - icon: linkedin
        href: https://www.linkedin.com/in/data-scientist-dhruv-garg/

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">
