project:
  type: website

website:
  title: "Dhruv Garg"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/vrudhgarg
      - icon: LinkedIn
        href: https://www.linkedin.com/in/data-scientist-dhruv-garg/
format:
  html:
    theme: cosmo
    css: styles.css



